### PR TITLE
Arena events: Added VehicleDescr event

### PR DESCRIPTION
**Pull request by gabrielhamel**

### CODE REVIEW

**Comment by dacite** [comment]
You added a lot of really cool events! I am very excited about all the things we can do now!

**Comment by gabrielhamel** [comment]
Yep, my goal is to cover every events ^^, I could cover entity method events if you want

**Review by dacite — APPROVED** [review]
Looks great!

**Comment by dacite** [comment]
I changed base to dev so you don't have to update one by one. You can merge both PRs to dev. I am new at this so let me know if I got this wrong

**Comment by gabrielhamel** [comment]
I got conflits with my others pull requests, but it's fine, isn't complicated to resolve. I don't see a benefit from merging to dev but it's better to work with a staging branch like "dev". And merge dev to main when you want to release a new version (or quick fix...).
Btw I don't have any rights for merging after your approval.

**Comment by dacite** [comment]
Okay, I'll treat `dev` branch like a staging branch. Then like you said, when its time a for a new release merge `dev` into `main.

After research, it looks like I will have to merge myself.

**Pull request merged**
